#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## Example 1: Using looping technique

def fib(n):
    sumby = []
    a, b = 1, 2
    for i in range(n - 1):
        a, b = b, a + b

        if a >= 4000000:
            print sum(sumby)
            break

        if a % 2 == 0:
            sumby.append(a)

        # if b % 2 == 0:
        #     sumby.append(b)

    return a

fib(100)